baseURL = "https://www.henriksommerfeld.se/"
languageCode = "en-gb"
title = "Henrik Sommerfeld's blog"
canonifyURLs = false
relativeURLs = false
buildDrafts = true
paginate = 5
pygmentsuseclasses = true
pygmentsstyle = "monokai"
preserveTaxonomyNames = true
disqusShortname = "henrik-sommerfeld"

[params]
    minifyBundles = false
    plausibleDomain = ""
description = "Yuniel Acosta Pérez's blog and portfilio. Mostly about computer related stuff."

[permalinks]
    article = "/:title/"