baseURL = "https://www.henriksommerfeld.se/"
languageCode = "en-gb"
title = "Nomatech"
canonifyURLs = false
relativeURLs = false
buildDrafts = false
paginate = 5
pygmentsuseclasses = true
pygmentsstyle = "monokai"
preserveTaxonomyNames = true
disqusShortname = "henrik-sommerfeld"
timeout = 60000
rssLimit = 10

[params]
minifyBundles = true
plausibleDomain = "henriksommerfeld.se"
logo = "images/logo.png"
description = "Yuniel Acosta Pérez's blog and portfilio. Mostly about computer related stuff."

[permalinks]
article = "/:title/"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"

################################ France Language ########################
[Languages.es]
languageName = "Es"
languageCode = "es"
contentDir = "content/spanish"
weight = 2
home = "Inicio"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "Home"
pre = "#"
url = "home"
weight = 1


[[Languages.en.menu.main]]
name = "about"
pre = "#"
url = "about"
weight = 2


[[Languages.en.menu.main]]
name = "services"
pre = "#"
url = "services"
weight = 3


[[Languages.en.menu.main]]
name = "portfolio"
pre = "#"
url = "portfolio"
weight = 4


[[Languages.en.menu.main]]
name = "testimonial"
pre = "#"
url = "team"
weight = 5


[[Languages.en.menu.main]]
name = "blog"
pre = "#"
url = "blog"
weight = 6


[[Languages.en.menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 7


################### French Navigation ########################
[[Languages.es.menu.main]]
name = "Inicio"
pre = "#"
url = "home"
weight = 1


[[Languages.es.menu.main]]
name = "Sobre mí"
pre = "#"
url = "about"
weight = 2


[[Languages.es.menu.main]]
name = "Servicios"
pre = "#"
url = "services"
weight = 3


[[Languages.es.menu.main]]
name = "Portafolio"
pre = "#"
url = "portfolio"
weight = 4


[[Languages.es.menu.main]]
name = "Testimonios"
pre = "#"
url = "team"
weight = 5


[[Languages.es.menu.main]]
name = "blog"
pre = "#"
url = "blog"
weight = 6


[[Languages.es.menu.main]]
name = "Contáctame"
pre = "#"
url = "contact"
weight = 7
