name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            # Remember to set this as a secret (i.e. secrets.GITHUB_TOKEN).
            # Don't forget to set the secret value in the project settings.
            branch: master # Or anything else
            # Use if your site is not hosted on the gh-pages branch.
            repo: you/you.github.io
            # Use if you're pushing to a different repo.
            # Dont add ".git" to the end of the URL (youl'll get 404s).
            hugoVersion: extended_0.80.0
            # Use if your site requires a specific version of Hugo.
            # Append "extended_" to the begining to use Hugo Extended.
            args: --gc --minify --cleanDestinationDir
            # Use if you want to pass some custom arguments to Hugo.
